### Switch on LED
POST http://localhost:10000/gpio/19/1

### Switch off LED
POST http://localhost:10000/gpio/19/0


### 
POST http://localhost:10000/gpio/RXD/0


###
POST http://localhost:10000/gpio/mode/TXD/PWM
