export var CLIENT_TYPE
;(function (CLIENT_TYPE) {
  CLIENT_TYPE["REMOTE_CONTROL"] = "REMOTE_CONTROL"
  CLIENT_TYPE["COCKPIT"] = "COCKPIT"
  CLIENT_TYPE["CAMERA"] = "CAMERA"
  CLIENT_TYPE["GPIO_VIEWER"] = "GPIO_VIEWER"
  CLIENT_TYPE["ACCELEROMETER"] = "ACCELEROMETER"
})(CLIENT_TYPE || (CLIENT_TYPE = {}))
